// components/Header.tsx
'use client'

import { useState } from 'react'
import { Download, Mail, Github, Linkedin, Menu, Sun, Moon, LogIn, LogOut, User, Edit3 } from 'lucide-react'
import { MdChromeReaderMode } from "react-icons/md"
import { useTheme } from '@/contexts/ThemeContext'
import { useAuth } from '@/contexts/AuthContext'
import { useTranslations } from '@/hooks/useTranslations'
import LanguageSwitcher from './ui/LanguageSwitcher'
import ThemeSwitcher from './ui/ThemeSwitcher'
import AuthModal from './ui/AuthModal'

interface HeaderProps {
  onMenuClick: () => void
  activeSection: 'resume' | 'showcase' | 'knowledge'
}

export default function Header({ onMenuClick, activeSection }: HeaderProps) {
  const { isDark, toggleDarkMode } = useTheme()
  const { user, isAuthenticated, logout, isEditMode, toggleEditMode } = useAuth()
  const { t } = useTranslations()
  const [showAuthModal, setShowAuthModal] = useState(false)
  const [authMode, setAuthMode] = useState<'login' | 'signup'>('login')
  const [showUserMenu, setShowUserMenu] = useState(false)
  
  const getSectionInfo = (section: string) => {
    switch (section) {
      case 'resume':
        return { title: t('header.resume.title'), subtitle: t('header.resume.subtitle') }
      case 'showcase':
        return { title: t('header.showcase.title'), subtitle: t('header.showcase.subtitle') }
      case 'knowledge':
        return { title: t('header.knowledge.title'), subtitle: t('header.knowledge.subtitle') }
      default:
        return { title: t('header.default.title'), subtitle: t('header.default.subtitle') }
    }
  }
  
  const sectionInfo = getSectionInfo(activeSection)
  
  const handleAuthClick = (mode: 'login' | 'signup') => {
    setAuthMode(mode)
    setShowAuthModal(true)
  }

  return (
    <>
      <header className="fixed top-0 left-0 right-0 h-16 border-b border-neutral-200 bg-white px-4 lg:px-8 flex items-center justify-between dark:bg-neutral-900 dark:border-neutral-700 transition-colors duration-300 z-30 backdrop-blur-sm bg-white/95 dark:bg-neutral-900/95">
      <div className="flex items-center gap-4">
        {/* Mobile Menu Button */}
        <button
          onClick={onMenuClick}
          className="lg:hidden p-2 text-neutral-600 hover:text-neutral-900 hover:bg-neutral-100 rounded-md transition-colors"
          aria-label={t('common.openMenu')}
        >
          <Menu className="w-5 h-5" />
        </button>
        
        <div className="flex items-center gap-3">
          <MdChromeReaderMode className="w-8 h-8 text-primary-600 dark:text-primary-400" />
          <div>
            <h1 className="text-lg lg:text-xl font-bold text-neutral-900 dark:text-neutral-100">{sectionInfo.title}</h1>
            <p className="text-xs lg:text-sm text-neutral-600 dark:text-neutral-400 hidden sm:block">{sectionInfo.subtitle}</p>
          </div>
        </div>
      </div>
      
      <div className="flex items-center gap-4">
        {/* Language Switcher */}
        <LanguageSwitcher />
        
        {/* Theme Switcher */}
        <ThemeSwitcher />

        {/* Social Links - Hidden on mobile */}
        <div className="hidden md:flex items-center gap-2">
          <a
            href="mailto:rheyno.apria@example.com"
            className="p-2 text-neutral-600 hover:text-primary-600 hover:bg-primary-50 rounded-md transition-colors dark:text-neutral-400 dark:hover:text-primary-400 dark:hover:bg-primary-900 dark:hover:bg-opacity-20"
            title={t('common.email')}
          >
            <Mail className="w-5 h-5" />
          </a>
          <a
            href="https://github.com/rheynoapria"
            target="_blank"
            rel="noopener noreferrer"
            className="p-2 text-neutral-600 hover:text-primary-600 hover:bg-primary-50 rounded-md transition-colors dark:text-neutral-400 dark:hover:text-primary-400 dark:hover:bg-primary-900 dark:hover:bg-opacity-20"
            title={t('common.github')}
          >
            <Github className="w-5 h-5" />
          </a>
          <a
            href="https://linkedin.com/in/rheynoapria"
            target="_blank"
            rel="noopener noreferrer"
            className="p-2 text-neutral-600 hover:text-primary-600 hover:bg-primary-50 rounded-md transition-colors dark:text-neutral-400 dark:hover:text-primary-400 dark:hover:bg-primary-900 dark:hover:bg-opacity-20"
            title={t('common.linkedin')}
          >
            <Linkedin className="w-5 h-5" />
          </a>
        </div>
        
        {/* Authentication Section */}
        {isAuthenticated ? (
          <div className="flex items-center gap-2">
            {/* Edit Mode Toggle for Admin */}
            {user?.role === 'admin' && (
              <button
                onClick={toggleEditMode}
                className={`flex items-center gap-2 px-3 py-2 rounded-md text-xs lg:text-sm font-medium transition-colors ${
                  isEditMode
                    ? 'bg-green-600 text-white hover:bg-green-700'
                    : 'bg-neutral-200 text-neutral-700 hover:bg-neutral-300 dark:bg-neutral-700 dark:text-neutral-300 dark:hover:bg-neutral-600'
                }`}
                title={isEditMode ? 'Exit Edit Mode' : 'Enter Edit Mode'}
              >
                <Edit3 className="w-4 h-4" />
                <span className="hidden sm:inline">{isEditMode ? 'Exit Edit' : 'Edit Mode'}</span>
              </button>
            )}

            {/* User Menu */}
            <div className="relative">
              <button
                onClick={() => setShowUserMenu(!showUserMenu)}
                className="flex items-center gap-2 px-3 py-2 text-neutral-600 hover:text-neutral-900 hover:bg-neutral-100 rounded-md transition-colors dark:text-neutral-400 dark:hover:text-neutral-100 dark:hover:bg-neutral-800"
              >
                <User className="w-4 h-4" />
                <span className="hidden sm:inline text-sm">{user?.name}</span>
              </button>

              {showUserMenu && (
                <div className="absolute right-0 mt-2 w-48 bg-white dark:bg-neutral-800 rounded-md shadow-lg border border-neutral-200 dark:border-neutral-700 z-50">
                  <div className="py-1">
                    <div className="px-4 py-2 text-sm text-neutral-700 dark:text-neutral-300 border-b border-neutral-200 dark:border-neutral-700">
                      <div className="font-medium">{user?.name}</div>
                      <div className="text-xs text-neutral-500 dark:text-neutral-400">{user?.email}</div>
                    </div>
                    <button
                      onClick={() => {
                        logout()
                        setShowUserMenu(false)
                      }}
                      className="flex items-center gap-2 w-full px-4 py-2 text-sm text-red-600 hover:bg-red-50 dark:hover:bg-red-900/20 transition-colors"
                    >
                      <LogOut className="w-4 h-4" />
                      Sign Out
                    </button>
                  </div>
                </div>
              )}
            </div>
          </div>
        ) : (
          <div className="flex items-center gap-2">
            <button
              onClick={() => handleAuthClick('login')}
              className="flex items-center gap-2 px-3 py-2 text-neutral-600 hover:text-neutral-900 hover:bg-neutral-100 rounded-md transition-colors dark:text-neutral-400 dark:hover:text-neutral-100 dark:hover:bg-neutral-800"
            >
              <LogIn className="w-4 h-4" />
              <span className="hidden sm:inline text-sm">Sign In</span>
            </button>
            <button
              onClick={() => handleAuthClick('signup')}
              className="flex items-center gap-2 px-3 py-2 bg-primary-600 text-white text-xs lg:text-sm font-medium rounded-md hover:bg-primary-700 focus:outline-none focus:ring-2 focus:ring-primary-500 focus:ring-offset-2 transition-colors dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-400"
            >
              <User className="w-4 h-4" />
              <span className="hidden sm:inline">Sign Up</span>
            </button>
          </div>
        )}

        {/* Download Resume Button */}
        <button className="flex items-center gap-2 px-3 lg:px-4 py-2 bg-neutral-200 text-neutral-700 text-xs lg:text-sm font-medium rounded-md hover:bg-neutral-300 focus:outline-none focus:ring-2 focus:ring-neutral-500 focus:ring-offset-2 transition-colors dark:bg-neutral-700 dark:text-neutral-300 dark:hover:bg-neutral-600 dark:focus:ring-neutral-400">
          <Download className="w-4 h-4" />
          <span className="hidden sm:inline">{t('common.downloadResume')}</span>
          <span className="sm:hidden">{t('common.cv')}</span>
        </button>
      </div>
    </header>

    {/* Auth Modal */}
    <AuthModal
      isOpen={showAuthModal}
      onClose={() => setShowAuthModal(false)}
      initialMode={authMode}
    />
    </>
  )
}

// src/components/layout/Header.vue
<script setup>
import { ref, computed } from 'vue'
import { useRoute } from 'vue-router'
import {
  Download, Mail, Github, Linkedin, Menu,
  LogIn, LogOut, User, Edit3, BookOpen,
} from 'lucide-vue-next'
import { useAuthStore } from '@/stores/auth'
import { useTranslations } from '@/composables/useTranslations'
import LanguageSwitcher from '@/components/widgets/LanguageSwitcher.vue'
import ThemeSwitcher from '@/components/widgets/ThemeSwitcher.vue'
import ThemeToggle from '@/components/widgets/ThemeToggle.vue'
import AuthModal from '@/components/widgets/AuthModal.vue'

const emit = defineEmits(['menuClick'])

const route = useRoute()
const auth = useAuthStore()
const { t } = useTranslations()

const showAuthModal = ref(false)
const authMode = ref('login')
const showUserMenu = ref(false)

const sectionInfo = computed(() => ({
  title: t(route.meta.titleKey || 'header.default.title'),
  subtitle: t(route.meta.subtitleKey || 'header.default.subtitle'),
}))

function openAuth(mode) {
  authMode.value = mode
  showAuthModal.value = true
}

function handleLogout() {
  auth.logout()
  showUserMenu.value = false
}
</script>

<template>
  <header
    class="fixed top-0 left-0 right-0 h-16 border-b theme-border theme-bg px-4 lg:px-8 flex items-center justify-between z-30 backdrop-blur-sm"
  >
    <div class="flex items-center gap-4">
      <button
        type="button"
        :aria-label="t('common.openMenu')"
        class="lg:hidden p-2 theme-text-secondary hover:theme-text rounded-md transition-colors"
        @click="emit('menuClick')"
      >
        <Menu class="w-5 h-5" />
      </button>

      <div class="flex items-center gap-3">
        <BookOpen class="w-8 h-8 theme-primary" />
        <div>
          <h1 class="text-lg lg:text-xl font-bold theme-text">
            {{ sectionInfo.title }}
          </h1>
          <p class="text-xs lg:text-sm theme-text-secondary hidden sm:block">
            {{ sectionInfo.subtitle }}
          </p>
        </div>
      </div>
    </div>

    <div class="flex items-center gap-2 lg:gap-4">
      <LanguageSwitcher />
      <ThemeSwitcher />
      <ThemeToggle />

      <!-- Social links (desktop only) -->
      <div class="hidden md:flex items-center gap-1">
        <a
          href="mailto:rheyno.apria@example.com"
          :title="t('common.email')"
          class="p-2 theme-text-secondary hover:theme-primary rounded-md transition-colors"
        >
          <Mail class="w-5 h-5" />
        </a>
        <a
          href="https://github.com/rheynoapria"
          target="_blank"
          rel="noopener noreferrer"
          :title="t('common.github')"
          class="p-2 theme-text-secondary hover:theme-primary rounded-md transition-colors"
        >
          <Github class="w-5 h-5" />
        </a>
        <a
          href="https://linkedin.com/in/rheynoapria"
          target="_blank"
          rel="noopener noreferrer"
          :title="t('common.linkedin')"
          class="p-2 theme-text-secondary hover:theme-primary rounded-md transition-colors"
        >
          <Linkedin class="w-5 h-5" />
        </a>
      </div>

      <!-- Auth section -->
      <template v-if="auth.isAuthenticated">
        <button
          v-if="auth.isAdmin"
          type="button"
          :title="auth.isEditMode ? 'Exit Edit Mode' : 'Enter Edit Mode'"
          :class="[
            'flex items-center gap-2 px-3 py-2 rounded-md text-xs lg:text-sm font-medium transition-colors',
            auth.isEditMode
              ? 'bg-green-600 text-white hover:bg-green-700'
              : 'theme-surface theme-text hover:opacity-80',
          ]"
          @click="auth.toggleEditMode()"
        >
          <Edit3 class="w-4 h-4" />
          <span class="hidden sm:inline">{{ auth.isEditMode ? 'Exit Edit' : 'Edit Mode' }}</span>
        </button>

        <div class="relative">
          <button
            type="button"
            class="flex items-center gap-2 px-3 py-2 theme-text-secondary hover:theme-text rounded-md transition-colors"
            @click="showUserMenu = !showUserMenu"
          >
            <User class="w-4 h-4" />
            <span class="hidden sm:inline text-sm">{{ auth.user?.name }}</span>
          </button>

          <div
            v-if="showUserMenu"
            class="absolute right-0 mt-2 w-48 theme-surface rounded-md shadow-lg border theme-border z-50"
          >
            <div class="py-1">
              <div class="px-4 py-2 text-sm theme-text border-b theme-border">
                <div class="font-medium">
                  {{ auth.user?.name }}
                </div>
                <div class="text-xs theme-text-secondary">
                  {{ auth.user?.email }}
                </div>
              </div>
              <button
                type="button"
                class="flex items-center gap-2 w-full px-4 py-2 text-sm text-red-600 hover:bg-red-50 dark:hover:bg-red-900/20 transition-colors"
                @click="handleLogout"
              >
                <LogOut class="w-4 h-4" />
                Sign Out
              </button>
            </div>
          </div>
        </div>
      </template>

      <template v-else>
        <button
          type="button"
          class="flex items-center gap-2 px-3 py-2 theme-text-secondary hover:theme-text rounded-md transition-colors"
          @click="openAuth('login')"
        >
          <LogIn class="w-4 h-4" />
          <span class="hidden sm:inline text-sm">Sign In</span>
        </button>
        <button
          type="button"
          class="flex items-center gap-2 px-3 py-2 theme-primary-bg text-white text-xs lg:text-sm font-medium rounded-md hover:opacity-90 focus:outline-none focus:ring-2 focus:ring-offset-2 transition-colors"
          @click="openAuth('signup')"
        >
          <User class="w-4 h-4" />
          <span class="hidden sm:inline">Sign Up</span>
        </button>
      </template>

      <!-- Download Resume Button -->
      <button
        type="button"
        class="flex items-center gap-2 px-3 lg:px-4 py-2 theme-surface theme-text text-xs lg:text-sm font-medium rounded-md hover:opacity-80 transition-colors"
      >
        <Download class="w-4 h-4" />
        <span class="hidden sm:inline">{{ t('common.downloadResume') }}</span>
        <span class="sm:hidden">{{ t('common.cv') }}</span>
      </button>
    </div>

    <AuthModal
      :is-open="showAuthModal"
      :initial-mode="authMode"
      @close="showAuthModal = false"
    />
  </header>
</template>
