// src/components/widgets/ThemeToggle.vue
<script setup>
import { Sun, Moon } from 'lucide-vue-next'
import { useThemeStore } from '@/stores/theme'

const theme = useThemeStore()
</script>

<template>
  <button
    type="button"
    aria-label="Toggle dark mode"
    class="h-9 w-9 inline-flex items-center justify-center rounded-md text-muted-foreground hover:text-foreground hover:bg-accent transition-colors"
    @click="theme.toggleDarkMode()"
  >
    <Sun
      v-if="theme.isDark"
      class="w-4 h-4"
    />
    <Moon
      v-else
      class="w-4 h-4"
    />
  </button>
</template>

// components/ui/ThemeToggle.tsx
'use client'

import { Sun, Moon } from 'lucide-react'
import { useTheme } from '@/contexts/ThemeContext'

interface ThemeToggleProps {
  className?: string
  showLabel?: boolean
}

export default function ThemeToggle({ className = "", showLabel = false }: ThemeToggleProps) {
  const { isDark, toggleDarkMode } = useTheme()

  return (
    <button
      onClick={toggleDarkMode}
      className={`p-2 text-neutral-600 hover:text-primary-600 hover:bg-primary-50 rounded-md transition-colors dark:text-neutral-400 dark:hover:text-primary-400 dark:hover:bg-primary-900 dark:hover:bg-opacity-20 ${className}`}
      title={isDark ? 'Switch to light mode' : 'Switch to dark mode'}
      aria-label={isDark ? 'Switch to light mode' : 'Switch to dark mode'}
    >
      <div className="flex items-center gap-2">
        {isDark ? (
          <Sun className="w-5 h-5" />
        ) : (
          <Moon className="w-5 h-5" />
        )}
        {showLabel && (
          <span className="text-sm font-medium">
            {isDark ? 'Light' : 'Dark'} Mode
          </span>
        )}
      </div>
    </button>
  )
}
